### ISSUE TITLE
Js and Blaze code versions

### ISSUE THREAD

**Issue by gam-ragnar** [PEM--/fview-animatedicon#1]
Thanks for your cool contributions especially of bringing  Hein Rutjes works to meteor! Is it possible to default your files to JS and Blaze and make coffeescript and Jade optional instead of the other way around? I guarantee everyone looking at your code understands JS/Blaze but not everyone wants to meddle with coffee or jade.
Thanks again for your cool contribs?
Tim

**Comment by PEM--** [comment]
Hi Tim. You're welcome. Always a pleasure to contribute when my scarce spare time allows me to do so.

Concerning your request, raw Blaze and vanilla JS require 2 times the amount of work while giving up a lot on the semantic. I fully understand your point but I unfortunately can't do too much about it.

Productivity... :sweat:
